oslabs-beta/BottleNetes

- PROMQL.md
- README.md
- package-lock.json
- package.json
- server/controllers/prometheusController.js
- server/server.js
> added promQL markdown

- server/controllers/prometheusController.js
- server/controllers/promqlController.js
- server/server.js
> added a very basic backend api for querying

- LATENCY.md
> added markdown for instructions accessing latency, LATENCY.md

- package-lock.json
- package.json
- src/components/ErrorRate.jsx
- src/components/Metrics.jsx
- src/components/Overview.jsx
- src/components/Pod.jsx
- src/components/PodGrid.jsx
- src/components/RequestLimit.jsx
- src/containers/MainContainer.jsx
- src/containers/MenuContainer.jsx
> feat: added basic state and components in maincontainer.jsx, created component files, installed chartjs

- package-lock.json
- package.json
- src/components/PodGrid.jsx
> install: installed react chartjs 2

- package.json
- src/components/Pod.jsx
- src/components/PodGrid.jsx
- src/containers/MainContainer.jsx
> fix: fixed package.json

- README.md
- package-lock.json
- server/controllers/promqlController.js
- [ x] I've titled my PR according to the [Conventional Commits spec](https://conventionalcommits.org)
- [ x] I've updated documentation (if appropriate)
> fix: updated package-lock.json for security

- src/components/ErrorRate.jsx
- src/components/Metrics.jsx
- src/components/Overview.jsx
- src/components/Pod.jsx
- src/components/PodGrid.jsx
- src/components/RequestLimit.jsx
- src/components/TestGrid.jsx
- src/containers/LogInContainer.jsx
- src/containers/MainContainer.jsx
- src/main.jsx
> feat: Adding TestGrid.jsx for testing purposes

- server/controllers/promqlController.js
- server/controllers/requestParsingController.js
- server/controllers/responseParsingController.js
- server/routes/api.js
- server/server.js
> added more api points

- src/components/Latency.jsx
- src/components/PodNameDisplay.jsx
- src/containers/MainContainer.jsx
> Pod name display/julie

- package-lock.json
- package.json
- server/controllers/k8sApiTest.js
- server/controllers/k8sController.js
- server/routes/k8sRouter.js
- server/server.js
- src/components/Latency.jsx
- src/components/Metrics.jsx
- src/components/Overview.jsx
- src/components/Pod.jsx
- src/components/PodGrid.jsx
- src/components/PodNameDisplay.jsx
- src/components/RequestLimit.jsx
- src/containers/MainContainer.jsx
- src/containers/MenuContainer.jsx
> Added features: pod restart, pod log viewing, and some styling. k8s/client-node version rolled back for bug fixing. Also some minor fixes and clean-up

- LICENSE
- src/components/Metrics.jsx
- src/components/PodGrid.jsx
- src/containers/MainContainer.jsx
[fix:]
- Adjusted colors for navBar;
- Add 2 buttons: Modify Replicas and Adjust Resources/Limits
- Adjust colors and transition for Heat Map buttons
- Added Legend titles for Historical Tracing and rounded points for each time steps
[todo:]
- Implement requests for k8s/replicas and k8s/requestsLimits for frontend;
- Fix Request vs. Limit graph for overflowing, bigger bars
- Remove Reset to Default button at the bottom of the page because the same button was implemented in the Heat Map
- Add features for retrieving password and signing out
- Fix force navigate to /dashboard endpoint even without logging in
- Add OAuth for GMmail and AWS Cognito
> Pod functionalities/mark funan

- server/controllers/k8sController.js
- server/routes/k8sRouter.js
- src/App.jsx
- src/CallbackHandler.jsx
- src/components/Pod.jsx
- src/components/PodGrid.jsx
- src/components/PodGridMetricSelection.jsx
- src/components/PodLogDisplay.jsx
- src/components/PodNameDisplay.jsx
- src/components/PodRestart.jsx
- src/components/QueryTimeWindowConfiguration.jsx
- src/components/RequestLimit.jsx
- src/containers/MainContainer.jsx
- src/containers/MenuContainer.jsx
- src/containers/SigninContainer.jsx
- src/hooks/useFetchData.js
feat:
- Completed functionality for replicas in the frontend
- Added deployment to certain pods on the dashboard
- Added a router to k8s endpoint to fetch deployments
- Removed points in the line chart because it does not look good when there are a lot of time steps
fix:
- Fixed scaleReplicas middleware. Parsed newReplicas back into a number
> New features and fixes

- server/controllers/k8sController.js
- server/controllers/promqlController.js
- server/controllers/responseParsingController.js
- src/components/Latency.jsx
- src/components/Metrics.jsx
- src/components/PodFilter.jsx
- src/components/PodGrid.jsx
- src/components/PodLogDisplay.jsx
- src/components/PodRestart.jsx
- src/components/PodSelector.jsx
- src/components/PodSorter.jsx
- src/containers/MainContainer.jsx
- Fixed the view of latency chart when there’s no data (using cpu metric’s timestamp as the default)
- Fixed an issue in Metric component (when a pod does not have both cpu and memory data, now it should still be able to show one of those)
- Fixed an issue in PodLogDisplay component (when a pod has multiple containers, now it will prompt the user to select one container to view the log)
- Added additional fetching of deployment info for each pod at backend. Updated API documents accordingly. 
- Added a pod selector dropdown. When toggle it will change the clickedPod state. Reset button will change it back to default.
- Added a sorter component. Currently it’s able to sort the pod grid based on cpu usage%, memory usage % and latency.  - Reset button will change it back to default.
- Added …
> feat: pod selector, sorter, filter

- src/Overview.css
- src/containers/SigninContainer.jsx
- src/containers/SignupContainer.jsx
> style: Added more styling to SigninContainer.jsx

- src/components/HeatMapComponents/PodGrid.jsx
- src/components/HeatMapComponents/QueryTimeWindowConfiguration.jsx
- src/components/HistoricalMetricsComponents/Metrics.jsx
- src/components/HistoricalMetricsComponents/TimeWindowSelector.jsx
- src/components/RequestLimitComponents/RequestLimitChart.jsx
- src/components/RequestLimitComponents/RequestLimitSorter.jsx
- src/containers/MainContainer.jsx
- src/hooks/useFetchData.js
> Feat: Time Window Selector functioning for metrics graph

- README.md
- package-lock.json
- package.json
- server/controllers/askAiController.ts
- src/components/Chatbot.tsx
- tailwind.config.js
> fix: fixed the chatbot a little bit

- README.md
- markdown/manual-setup-instruction.md
> getting rid of extra env file

- src/components/Chatbot.tsx
> fix: fixed prune logic in chatbot

- README.md
> italicized the tagline in readme
